# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Marek Küthe <m.k@mk16.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

line_endings = "Unix"
indent_type = "Spaces"

[sort_requires]
enabled = false
