# SPDX-FileCopyrightText: Copyright (C) 2024-2025 Marek Küthe <m.k@mk16.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

when:
  - event: tag

steps:
  - name: release
    environment:
      CODEBERG_GIT_USERNAME:
        from_secret: codeberg_git_username
      CODEBERG_GIT_PASSWORD:
        from_secret: codeberg_git_password
    image: codeberg.org/mark22k/ci:latest
    pull: true
    commands:
      - export PATH="$HOME/.local/bin:$PATH"
      - eval "$(luarocks path --bin)"
      - . "$HOME/.cargo/env"
      - apt-get update
      - make debian
      - |
        for FILE in ../mping-sender_*.deb; do
          curl --user $CODEBERG_GIT_USERNAME:$CODEBERG_GIT_PASSWORD --upload-file $FILE https://codeberg.org/api/packages/mark22k/debian/pool/stable/main/upload
        done
